FROM tomcat:7.0.67-jre7
RUN echo "Asia/Shanghai" > /etc/timezone
WORKDIR /usr/local/tomcat/
COPY tomcat-users.xml conf/tomcat-users.xml
COPY server.xml conf/server.xml
COPY context.xml conf/context.xml
#RUN rm -rf webapps/*
RUN wget -q -O webapps/bang.war http://192.168.42.13/bang.war && wget -q -O webapps/bang-pay.war http://192.168.42.13/bang-pay.war
RUN wget -q -O lib/commons-pool-1.5.6.jar http://192.168.42.13/commons-pool-1.5.6.jar && wget -q -O lib/jedis-2.1.0.jar http://192.168.42.13/jedis-2.1.0.jar && wget -q -O lib/tomcat-redis-session-manager-tomcat-7-1.1.jar http://192.168.42.13/tomcat-redis-session-manager-tomcat-7-1.1.jar
#RUN wget -q -O lib/commons-jci-fam-1.0.jar http://192.168.42.12/commons-jci-fam-1.0.jar
COPY run.sh /run.sh
RUN chmod +x /run.sh
#ENTRYPOINT ["sh","bin/catalina.sh","start"]
CMD ["/run.sh"]
